### PR TITLE
Fixed icon for FinderSync. Now dynamically adjusts with dark mode wit…

### PR DESCRIPTION
**Pull request by Camji55**
…hout the need to relaunch Finder.

### CODE REVIEW

**Comment by Camji55** [comment]
Screen Shot 2019-04-19 at 12 39 17 PM
Screen Shot 2019-04-19 at 12 39 33 PM

**Comment by Camji55** [comment]
And congrats on making to Daily Trending page! 🎉

**Comment by Camji55** [comment]
Also added some community templates.

**Comment by Ji4n1ng** [comment]
I never expected to see my project on GitHub Trending. And what is even more unexpected is that this is my first open source project for users. Thank you so much. Your contribution means a lot to me. It is an honor and a pleasure to work with you. 😀

**Pull request merged**
