### PR TITLE
Added Terminal selector

### PR DESCRIPTION
**Pull request by Camji55**
Added a Terminal selector dialog when a user clicks on the app.

Screen Shot 2019-04-16 at 12 11 09 PM

### CODE REVIEW

**Comment by Camji55** [comment]
Let me know your thoughts on the Dialog title and description. I can change it to suit your needs. I also updated the English README. Don't know Chinese, so I left that one as is.

**Comment by Ji4n1ng** [comment]
Thank you very much for your contribution. This is a very good way for the user to choose which terminal to open. But I think this may affect efficiency if a selection box appears each time the app is running. So a better way is that the selection box only appears when you run the app for the first time. And I will modify it next. Thank you very much. 😀

**Comment by Camji55** [comment]
Glad you like it! That’s a great point about efficiency and I like the idea of setting the default after first launch. Curiously, how would a user change the default? Possibly a preference pane?

**Comment by Ji4n1ng** [comment]
Version 0.2.0 has added the terminal selector thanks to your contribution. Now application uses `UserDefaults` to store the selected terminal identifier. So user need to run command `defaults remove wang.jianing.OpenInTerminal OIT_TerminalBundleIdentifier` to reset the default terminal. You can read README.

**Comment by Camji55** [comment]
Awesome!

**Pull request merged**
